"""geo phone conversation status media key

Revision ID: 3715a0d52953
Revises: c1a1f6e64bbc
Create Date: 2026-09-14 04:14:20.661134

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3715a0d52953'
down_revision: str | None = 'c1a1f6e64bbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _normalize_phone(raw: str | None) -> str | None:
    """Backfill autocontenido (no importa codigo de la app, que puede evolucionar)."""
    if not raw:
        return None
    digits = "".join(char for char in raw if char.isdigit())
    if len(digits) == 13 and digits.startswith("0051"):
        national = digits[4:]
    elif len(digits) == 11 and digits.startswith("51"):
        national = digits[2:]
    elif len(digits) == 9:
        national = digits
    else:
        return None
    if len(national) == 9 and national.startswith("9"):
        return f"+51{national}"
    return None


def _backfill_phone_normalized() -> None:
    connection = op.get_bind()
    rows = connection.execute(
        sa.text("SELECT id, phone FROM users WHERE phone IS NOT NULL")
    ).fetchall()
    seen: set[str] = set()
    for user_id, phone in rows:
        normalized = _normalize_phone(phone)
        if normalized is None or normalized in seen:
            continue
        seen.add(normalized)
        connection.execute(
            sa.text("UPDATE users SET phone_normalized = :normalized WHERE id = :user_id"),
            {"normalized": normalized, "user_id": user_id},
        )


def _backfill_geo_from_text(table: str) -> None:
    """Mejor esfuerzo: cruza el distrito/ciudad legado con el ubigeo por nombre.

    Primero intenta interpretar ``city`` como departamento; si no hay match,
    como provincia (datos legados usaban a veces la provincia como ciudad).
    """
    connection = op.get_bind()
    for city_column in ("department", "province"):
        connection.execute(
            sa.text(
                f"""
                UPDATE {table} AS target
                SET district_id = district.id,
                    province_id = district.province_id,
                    department_id = district.department_id
                FROM districts AS district
                JOIN provinces AS province ON province.id = district.province_id
                JOIN departments AS department ON department.id = district.department_id
                WHERE target.district_id IS NULL
                  AND target.district IS NOT NULL
                  AND lower(btrim(target.district)) = lower(district.name)
                  AND lower(btrim(target.city)) = lower({city_column}.name)
                """
            )
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('provinces',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_provinces_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces'))
    )
    op.create_index(op.f('ix_provinces_code'), 'provinces', ['code'], unique=True)
    op.create_index(op.f('ix_provinces_department_id'), 'provinces', ['department_id'], unique=False)
    op.create_table('districts',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('province_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_districts_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_districts_province_id_provinces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=True)
    op.create_index(op.f('ix_districts_department_id'), 'districts', ['department_id'], unique=False)
    op.create_index(op.f('ix_districts_province_id'), 'districts', ['province_id'], unique=False)
    op.add_column('conversations', sa.Column('status', sa.Enum('open', 'closed', 'archived', name='conversation_status', native_enum=False, create_constraint=True, length=20), server_default='open', nullable=False))
    op.add_column('conversations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.add_column('customer_profiles', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('customer_profiles', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('customer_profiles', sa.Column('district_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customer_profiles_department_id'), 'customer_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_district_id'), 'customer_profiles', ['district_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_province_id'), 'customer_profiles', ['province_id'], unique=False)
    op.create_foreign_key(op.f('fk_customer_profiles_province_id_provinces'), 'customer_profiles', 'provinces', ['province_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_customer_profiles_department_id_departments'), 'customer_profiles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_customer_profiles_district_id_districts'), 'customer_profiles', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    _backfill_geo_from_text("customer_profiles")
    op.drop_column('repair_request_images', 'url')
    op.add_column('repair_requests', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('repair_requests', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('repair_requests', sa.Column('district_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_repair_requests_department_id'), 'repair_requests', ['department_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_district_id'), 'repair_requests', ['district_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_province_id'), 'repair_requests', ['province_id'], unique=False)
    op.create_foreign_key(op.f('fk_repair_requests_province_id_provinces'), 'repair_requests', 'provinces', ['province_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_repair_requests_district_id_districts'), 'repair_requests', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_repair_requests_department_id_departments'), 'repair_requests', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    _backfill_geo_from_text("repair_requests")
    op.add_column('technicians', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('technicians', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('technicians', sa.Column('district_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_technicians_department_id'), 'technicians', ['department_id'], unique=False)
    op.create_index(op.f('ix_technicians_district_id'), 'technicians', ['district_id'], unique=False)
    op.create_index(op.f('ix_technicians_province_id'), 'technicians', ['province_id'], unique=False)
    op.create_foreign_key(op.f('fk_technicians_department_id_departments'), 'technicians', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_technicians_province_id_provinces'), 'technicians', 'provinces', ['province_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_technicians_district_id_districts'), 'technicians', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('phone_normalized', sa.String(length=16), nullable=True))
    _backfill_phone_normalized()
    op.create_index(op.f('ix_users_phone_normalized'), 'users', ['phone_normalized'], unique=True)
    op.create_index('ix_orders_customer_status', 'orders', ['customer_id', 'status'], unique=False)
    op.create_index('ix_orders_technician_status', 'orders', ['technician_id', 'status'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_reviews_technician_created', 'reviews', ['technician_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_technician_created', table_name='reviews')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_orders_technician_status', table_name='orders')
    op.drop_index('ix_orders_customer_status', table_name='orders')
    op.drop_index(op.f('ix_users_phone_normalized'), table_name='users')
    op.drop_column('users', 'phone_normalized')
    op.drop_constraint(op.f('fk_technicians_district_id_districts'), 'technicians', type_='foreignkey')
    op.drop_constraint(op.f('fk_technicians_province_id_provinces'), 'technicians', type_='foreignkey')
    op.drop_constraint(op.f('fk_technicians_department_id_departments'), 'technicians', type_='foreignkey')
    op.drop_index(op.f('ix_technicians_province_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_district_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_department_id'), table_name='technicians')
    op.drop_column('technicians', 'district_id')
    op.drop_column('technicians', 'province_id')
    op.drop_column('technicians', 'department_id')
    op.drop_constraint(op.f('fk_repair_requests_department_id_departments'), 'repair_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_repair_requests_district_id_districts'), 'repair_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_repair_requests_province_id_provinces'), 'repair_requests', type_='foreignkey')
    op.drop_index(op.f('ix_repair_requests_province_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_district_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_department_id'), table_name='repair_requests')
    op.drop_column('repair_requests', 'district_id')
    op.drop_column('repair_requests', 'province_id')
    op.drop_column('repair_requests', 'department_id')
    op.add_column('repair_request_images', sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_customer_profiles_district_id_districts'), 'customer_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_profiles_department_id_departments'), 'customer_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_profiles_province_id_provinces'), 'customer_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_customer_profiles_province_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_district_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_department_id'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'district_id')
    op.drop_column('customer_profiles', 'province_id')
    op.drop_column('customer_profiles', 'department_id')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_column('conversations', 'closed_at')
    op.drop_column('conversations', 'status')
    op.drop_index(op.f('ix_districts_province_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_department_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_provinces_department_id'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_code'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
