"""initial schema

Revision ID: c1a1f6e64bbc
Revises: 
Create Date: 2026-09-12 15:36:08.847280

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c1a1f6e64bbc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('specialties',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties'))
    )
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=True)
    op.create_index(op.f('ix_specialties_slug'), 'specialties', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), server_default='Lima', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customer_profiles_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('quotation_created', 'quotation_accepted', 'order_status_changed', 'message_new', 'review_created', 'system', name='notification_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('technicians',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offers_home_service', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('offers_workshop_service', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('workshop_address', sa.String(length=255), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_technicians_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technicians')),
    sa.UniqueConstraint('user_id', name=op.f('uq_technicians_user_id'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('repair_requests',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_technician_id', sa.UUID(), nullable=True),
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), server_default='Lima', nullable=False),
    sa.Column('modality', sa.Enum('home', 'workshop', name='modality', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'quoted', 'accepted', 'in_progress', 'completed', 'cancelled', name='request_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], name=op.f('fk_repair_requests_assigned_technician_id_technicians'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_repair_requests_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_repair_requests_specialty_id_specialties'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_requests'))
    )
    op.create_index(op.f('ix_repair_requests_assigned_technician_id'), 'repair_requests', ['assigned_technician_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_customer_id'), 'repair_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_specialty_id'), 'repair_requests', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_status'), 'repair_requests', ['status'], unique=False)
    op.create_index('ix_repair_requests_status_created_at', 'repair_requests', ['status', 'created_at'], unique=False)
    op.create_table('technician_specialties',
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('specialty_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_technician_specialties_specialty_id_specialties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_technician_specialties_technician_id_technicians'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technician_id', 'specialty_id', name=op.f('pk_technician_specialties'))
    )
    op.create_table('quotations',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preliminary_diagnosis', sa.Text(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', name='quotation_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], name=op.f('fk_quotations_request_id_repair_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_quotations_technician_id_technicians'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('request_id', 'technician_id', name='uq_quotations_request_technician')
    )
    op.create_index(op.f('ix_quotations_request_id'), 'quotations', ['request_id'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index(op.f('ix_quotations_technician_id'), 'quotations', ['technician_id'], unique=False)
    op.create_table('repair_request_images',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], name=op.f('fk_repair_request_images_request_id_repair_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_request_images'))
    )
    op.create_index(op.f('ix_repair_request_images_request_id'), 'repair_request_images', ['request_id'], unique=False)
    op.create_table('orders',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='order_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_orders_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_orders_quotation_id_quotations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], name=op.f('fk_orders_request_id_repair_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_orders_technician_id_technicians'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('quotation_id', name=op.f('uq_orders_quotation_id'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_request_id'), 'orders', ['request_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_technician_id'), 'orders', ['technician_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_items_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_items'))
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('conversations',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_conversations_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_conversations_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], name=op.f('fk_conversations_request_id_repair_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_conversations_technician_id_technicians'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('order_id', name=op.f('uq_conversations_order_id')),
    sa.UniqueConstraint('request_id', 'technician_id', name='uq_conversations_request_technician')
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_request_id'), 'conversations', ['request_id'], unique=False)
    op.create_index(op.f('ix_conversations_technician_id'), 'conversations', ['technician_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='order_status_old', native_enum=False, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='order_status_new', native_enum=False, length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_order_status_history_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_reviews_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_reviews_technician_id_technicians'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=True)
    op.create_index(op.f('ix_reviews_technician_id'), 'reviews', ['technician_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_reviews_technician_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_conversations_technician_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_request_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_orders_technician_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_request_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_repair_request_images_request_id'), table_name='repair_request_images')
    op.drop_table('repair_request_images')
    op.drop_index(op.f('ix_quotations_technician_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_request_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_table('technician_specialties')
    op.drop_index('ix_repair_requests_status_created_at', table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_status'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_specialty_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_customer_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_assigned_technician_id'), table_name='repair_requests')
    op.drop_table('repair_requests')
    op.drop_table('user_roles')
    op.drop_table('technicians')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_specialties_slug'), table_name='specialties')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
